trigger:
- main

pool:
  vmImage: ubuntu-latest







stages: 
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: "Do the build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - scrpit: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - scrpit: echo deploy to QA